# Домашние задания второго урока.

**1. В следующих степах потренируемся использовать изученные функции.**

**Начнем с простого вопроса: что произойдет в результате выполнения следующей команды?**
```python
import pandas as pnds
```
* Сможем использовать библиотеку pandas, обращаясь и как pandas, и как pnds
* Вовсе не сможем использовать библиотеку, потому что использовали сокращение pnds, а не pd
* **Сможем использовать библиотеку pandas, обращаясь к ней как pnds**

**2. Отлично! Теперь поработаем с данными о поездках на такси в Нью-Йорке, где также имеется информация о погодных условиях и выходных днях.**  

* pickup_dt – период с точностью до часа

* pickup_month – месяц

* borough – район Нью-Йорка, из которого был сделан заказ (5 районов + аэропорт)

* pickups – число поездок за период (час)

* hday – является ли день праздничным/выходным; Y - да,  N - нет

* spd – скорость ветра в милях в час

* vsb – видимость

* temp – температура в градусах Фаренгейта

* dewp – точка росы по Фаренгейту

* slp – давление

* pcp_01 – количество осадков за час

* pcp_06 – количество осадков за 6 часов

* pcp_24 – количество осадков за 24 часа

* sd – глубина снега в дюймах
      

**Но перед тем, как приступать к работе, давайте загрузим данные. На LMS путь к данным лежит в переменной path_to_file (условно, path_to_file = "/some/path/to/file.csv"). Импортируйте библиотеку pandas, а затем загрузите данные по вышеупомянутой ссылке. **

**Результат сохраните в переменную taxi.**

In [ ]:
import pandas as pd
taxi = pd.read_csv(path_to_file)

**3. Проверьте, сколько всего строк и столбцов имеется в датасете.**

* 21715 столбцов, 14 строк
* **29101 строка, 14 столбцов**
* 21715 строк, 14 столбцов
* 29101 столбец, 14 строк
* 26058 строк, 14 столбцов

**4. Давайте посмотрим на типы колонок. Все ли из них считались правильно? В качестве ответа выберите тип, преобладающий в датасете.**

* int64
* **float64**
* datetime64
* object

**5. В названиях столбцов pcp 01, pcp 06, pcp 24 встречается пробел. Это не очень удобно, если в дальнейшем вы планируете обращаться к колонкам через точку, без использования кавычек и скобочек.** 

**Замените пробел в названиях на знак нижнего подчеркивания.**

**Данные сохранены в переменную taxi. Данные должны быть изменены в этом же датафрейме.**

In [ ]:
taxi = taxi.rename(columns={'pcp 01': 'pcp_01', 'pcp 06': 'pcp_06', 'pcp 24': 'pcp_24'})

**6. Вас попросили узнать, сколько записей (строк) в датафрейме относятся к району Манхэттен (Manhattan). Получить ответ на данный вопрос можно было бы, например, с помощью следующей команды:**
```python
taxi.query("borough == 'Manhattan'").shape[0]
```
**А если мы хотим посмотреть, сколько раз встречается каждый из районов? Неужели придется использовать подобную конструкцию для каждого уровня переменной? Здесь на помощь приходит метод value_counts(), подробнее о котором можно почитать в конспекте!**

**Сколько раз в данных встречается район Бруклин (Brooklyn)?**

Ответ: `4343`

**7. Следующая задача: выяснить, из какого района было совершено наибольшее количество поездок за весь период. Для начала, посчитайте общее количество поездок (pickups), без группировки.**

Ответ: `14265773`

**8. А теперь сгруппируйте данные по району (borough) и укажите, из какого пункта было совершено больше всего поездок.**

* Staten Island
* Brooklyn
* Queens
* Bronx
* **Manhattan**

**9. ⭐️Задание со звёздочкой!⭐️**

**Еще несколько полезных методов в pandas! Возможно, в предыдущем степе вы просто посмотрели на данные или отсортировали значения. Ускорить данный процесс в дальнейшем помогут методы idxmin() и idxmax(), которые возвращают индекс минимального или максимального значения.**

idxmin – индекс минимального значения

idxmax – индекс максимального значения

**Сохраните название района с наименьшим числом поездок в переменную min_pickups, применив подходящий метод.**

**Исходные данные сохранены в переменную taxi.**

In [ ]:
min_pickups = taxi \
    .groupby(['borough']) \
    .aggregate({'pickups': 'sum'}) \
    .sort_values('pickups', ascending=False)  \
    .idxmin()

**10. Продолжим изучение данных и посмотрим на число поездок в выходные дни. Сгруппируйте данные по двум признакам: району города и является ли день выходным (колонки borough и hday). Сравните среднее число поездок, и выберите районы, из которых по праздникам в среднем поступает больше заказов, чем в обычные дни.**

* Staten Island
* Brooklyn
* Bronx
* **Queens**
* **EWR**
* Manhattan

**11. Для каждого района посчитайте число поездок по месяцам. Отсортируйте полученные значения по убыванию и сохраните результирующий датафрейм в pickups_by_mon_bor.**

**Обратите внимание, что итоговый датасет должен состоять из 3-х колонок - pickup_month, borough, pickups.**

**Данные сохранены в переменную taxi.**

In [ ]:
pickups_by_mon_bor = taxi \
    .groupby(['borough', 'pickup_month'], as_index=False) \
    .aggregate({'pickups': 'sum'}) \
    .sort_values('pickups', ascending=False)

**11. 💀 Сложное задание! 💀**

**Теперь задача посложнее! Попрактикуемся в написании собственных функций и их применении к датафрейму. Поскольку данные о поездках в Нью-Йорке, температура представлена в градусах Фаренгейта.**

**Напишите функцию temp_to_celcius, которая получает на вход колонку с температурой в °F, и возвращает значения, переведенные в градусы Цельсия.**

Формула:

t °С = 5/9 (t °F - 32)

Пример работы функции:
```python
> taxi['temp'][:5]
0    30.0
1    30.0
2    30.0
3    30.0
4    30.0

> taxi['temp_C'] = temp_to_celcius(taxi['temp'])
> taxi['temp_C'][:5]
0   -1.111111
1   -1.111111
2   -1.111111
3   -1.111111
4   -1.111111
```
**NB! В окошке ниже надо написать только саму функцию. Так как урок посвящён pandas, то и всё содержимое функции должно быть выполнено средствами этой библиотеки - убедитесь, что на выходе она даёт pandas Series.**

In [ ]:
def temp_to_celcius(temp):
    return (temp - 32) * 5 / 9